### PR TITLE
fix docker build error on m1

### PR DESCRIPTION
**Pull request by CraigMChen**
#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
resolve docker build error `qemu: uncaught target signal 11 (Segmentation fault) - core dumped` on Apple Silicon

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @johnlanni 

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dspo** [comment]
https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images

**Comment by sfwn** [comment]
We should check if hongkong CI's docker version support buildkit. I see it is a buildkit feature.

**Comment by dspo** [comment]
```shell
if [[ `docker version -f '{{.Client.Experimental}}'` == 'true' ]]; then
    echo "docker version client experimental is true"
fi
```

**Comment by CraigMChen** [comment]
Randomly get error `qemu: uncaught target signal 11 (Segmentation fault) - core dumped` when build on m1.

There may not be any good solutions at the moment.

https://github.com/docker/for-mac/issues/5123

**Pull request closed without merging**
