### PR TITLE
autotest step add custom-script type

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
autotest step add custom-script type

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=223155&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIl0sImFzc2lnbmVlSURzIjpbIjEwMDEyMDUiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=506&type=TASK)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  autotest step add custom-script type            |
| 🇨🇳 中文    | 自动化步骤支持自定义脚本的执行             |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chengjoey** [comment]
image
image
image

**Comment by sfwn** [comment]
image
Does it support multi-line?

**Comment by chengjoey** [comment]
> image
> Does it support multi-line?

don`t support, now can use '\ &&' execute multi commands

**Comment by chengjoey** [comment]
> image
> Does it support multi-line?

support multi line
image
image

**Comment by sfwn** [comment]
User should select a prepared env, such as `python`, `java` and `others`.
`Image` is a very geek option for experts, hidden default.

**Review by Effet — CHANGES_REQUESTED** [review]
I dont want multi-line, i want textarea!

**Pull request closed without merging**
