### PR TITLE
modify workbench copywriting

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of this PR

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:
modify workbench copywriting

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda-org.erda.cloud/erda/dop/projects/387/issues/all?id=204682&issueFilter__urlQuery=eyJpdGVyYXRpb25JRHMiOls0MzEsNDI5XSwic3RhdGVCZWxvbmdzIjpbIk9QRU4iLCJXT1JLSU5HIiwiV09OVEZJWCIsIlJFT1BFTiJdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMjA1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=BUG)

### CODE REVIEW

**Comment by Effet** [comment]
post page screenshot that affected by your changes

**Review by sfwn — APPROVED** [review]

**Comment by chengjoey** [comment]
image

**Pull request merged**
