### PR TITLE
feat: pod monitoring charts modified to show Pods as the smallest unit

### PR DESCRIPTION
**Pull request by CeerDecy**
#### What this PR does / why we need it:
pod monitoring charts modified to show Pods as the smallest unit

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=623909&iterationID=12783&type=BUG)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      pod monitoring charts modified to show Pods as the smallest unit       |
| 🇨🇳 中文    |       将Pod详情页的监控图表修改为以Pod为最小单位显示       |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by iutx — APPROVED** [review]
LGTM @sfwn

**Comment by sfwn** [comment]
cc @chengjoey

**Comment by chengjoey** [comment]
CMP are different with amp, because our amp service only one service container in pod, so it could use pod as container monitor, but cmp monitor all pods, redis, clickhouse and other pods has more than one container, how could we see different container monitor if use pod as smallest unit.

i suggest use contaienr name or other container unique key as smallest unit

**Review by chengjoey — APPROVED** [review]
because the benefits of using pod as the smallest unit are greater than containers, and there are fewer pods with multiple containers, and they are usually sidecar containers, we still use pod as the smallest unit until we can solve the pause problem.

**Pull request merged**
