### PR TITLE
fix testscene-run action scene name to display abnormally

### PR DESCRIPTION
**Pull request by pipipipipi43**
#### What type of this PR

Add one of the following kinds:

/kind bug

#### What this PR does / why we need it:

[erda-issue](https://erda.cloud/erda/dop/projects/387/issues/bug?id=205935&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6InRhYmxlIiwiY2hpbGRyZW5WYWx1ZSI6eyJrYW5iYW4iOiJkZWFkbGluZSJ9fQ%3D%3D&iterationID=431&type=BUG)

#### Which issue(s) this PR fixes:

Fix the problem that the task name that has been filled in will be cleared when the test space is selected for the execution of the action of the test plan

/assign @Effet

### CODE REVIEW

**Comment by ZLValien** [comment]
Please indicate in the title what error is fixed。
component protocol is code details

**Comment by sfwn** [comment]
add unit test for patch.

**Comment by sfwn** [comment]
still not match codecov patch.

**Review by sfwn — APPROVED** [review]

**Pull request merged**
