### PR TITLE
feature(dicehub): extension spec parse supportedVersions field from `supportedErdaVersions` tag

### PR DESCRIPTION
**Pull request by sfwn**
#### What type of this PR

/kind feature

#### What this PR does / why we need it:

Erda Version 1.1 is lower than old Dice Version like 3.21. So cli push ext will delete ext needed.

Add new field `supportedErdaVersions` in spec.yml and version from erda 1.0 to distinguish dice version.

#### Which issue(s) this PR fixes:

- [Erda Cloud Issue Link](https://erda.cloud/erda/workBench/projects/387/issues/all?id=65286&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiOTIiXX0%3D&issueTable__urlQuery=eyJwYWdlTm8iOjF9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=429&type=TASK)

#### Specified Reviewers:

/assign @Effet 

#### Need cherry-pick to release versions?

No. Just for 1.1.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Effet** [comment]
have you added supportedErdaVersion in all of actions?

**Comment by sfwn** [comment]
> have you added supportedErdaVersion in all of actions?

I'm working on this now.

**Comment by Effet** [comment]
As its dependency, i will start to review after all actions are refactored.

**Comment by sfwn** [comment]
> As its dependency, i will start to review after all actions are refactored.

Please see the PRs I referenced.
I tested in dev and passed.

**Pull request merged**
