### PR TITLE
pipeline merge branch allow wildcard

### PR DESCRIPTION
**Pull request by JdaieLin**
#### What type of this PR

Add one of the following kinds:
feature

#### What this PR does / why we need it:

pipeline merge branch allow wildcard

e.g.

```
on:
   merge:
       branches: 
           - feature/*
```

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sfwn — DISMISSED** [review]

**Comment by sfwn** [comment]
Commit must be signed.

**Review by JdaieLin — COMMENTED** [review]
ok

**Review by sfwn — APPROVED** [review]

**Comment by sfwn** [comment]
linked issue: #949

**Pull request merged**
