### PR TITLE
Pipeline add `pipeline_before_exec_precheck` type of aop tunepoint

### PR DESCRIPTION
**Pull request by sfwn**
#### What type of PR is this?

feature

#### What this PR does / why we need it:

Pipeline add `precheck` type of aop tunepoint.

Pipeline network hook will use it. doc: https://www.yuque.com/erda-project/design/sdvvwl

### CODE REVIEW

**Review by kakj-go — COMMENTED** [review]
I think pipeline_precheck cannot express the meaning of pre-run check, what fields should be used if there is a check before creation later

**Comment by Effet** [comment]
> Pipeline network hook will use it.

what is network hook ?

**Comment by Effet** [comment]
give us some example pls

**Comment by sfwn** [comment]
> give us some example pls

https://www.yuque.com/erda-project/design/sdvvwl

**Review by Effet — APPROVED** [review]

**Review by Effet — APPROVED** [review]

**Pull request closed without merging**
