### PR TITLE
refactor: put conf besides app cmd

### PR DESCRIPTION
**Pull request by sfwn**
#### What this PR does / why we need it:

put conf besides app cmd

#### Specified Reviewers:

/assign @Effet @snakorse @sixther-dc 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  put conf besides app cmd            |
| 🇨🇳 中文    |  将 app conf 放置在 cmd 下        |

### CODE REVIEW

**Comment by Effet** [comment]
can you go:embed i18n folder?

**Comment by innerpeacez** [comment]
Is .gitkeep file necessary? @sfwn

**Comment by sfwn** [comment]
> can you go:embed i18n folder?

It will be handled later by @sixther-dc

**Comment by sfwn** [comment]
> Is .gitkeep file necessary? @sfwn

Yes, I want to make it clear for user to know that he/she can use `conf` and `common-conf` two dirs.

**Pull request merged**
