### PR TITLE
fix table audit_history error

### PR DESCRIPTION
**Pull request by QvodSoldier**
#### What type of this PR
/kind bug

#### What this PR does / why we need it:
If the fields of table `dice_audit_history` and table `dice_audit` are inconsistent, the audit archive will fail

#### Specified Reviewers:

/assign @Effet

### CODE REVIEW

**Review by Effet — CHANGES_REQUESTED** [review]
since migration lint passed, can you explain how you maintain compatibility after change column from NULL to NOT NULL?

**Comment by QvodSoldier** [comment]
The query sql used to be  `db.Where("fdp_project_id = ? or fdp_project_id is NULL", "")` , Should I delete ‘is null’ afterwards?
image

**Comment by Effet** [comment]
`or` looks no problem for compaitibity

**Review by Effet — APPROVED** [review]

**Pull request merged**
