### PR TITLE
feat(resource): update request resource with ratio directly

### PR DESCRIPTION
**Pull request by Muzry**
#### What type of this PR

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:

feat(resource): update request resource with ratio directly

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @luobily

### CODE REVIEW

**Review by luobily — COMMENTED** [review]
/lgtm

**Comment by luobily** [comment]
cc @sixther-dc

**Review by sixther-dc — COMMENTED** [review]
/lgtm

**Review by luobily — DISMISSED** [review]

**Review by sfwn — APPROVED** [review]

**Pull request merged**
