### PR TITLE
fix: update to solve the slow sql and order problems

### PR DESCRIPTION
**Pull request by littlejiancc**
#### What type of this PR

Add one of the following kinds:
/kind bugfix

#### What this PR does / why we need it:
fix: update to solve the slow sql and order problems

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?
cherry-pick release/1.4
cherry-pick release/1.5-alpha1

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sfwn — APPROVED** [review]

**Comment by littlejiancc** [comment]
cherry-pick release/1.4

**Comment by littlejiancc** [comment]
cherry-pick release/1.5-alpha1

**Pull request merged**
