### PR TITLE
Xlsx package upgrade to v3.2.4

### PR DESCRIPTION
**Pull request by shuofan**
#### What type of this PR
bug

#### What this PR does / why we need it:
Fix empty cells in Mac OS Numbers

#### Specified Reviewers:

/assign @Effet @sfwn 

#### Need cherry-pick to release versions?
Yes  release/1.1

### CODE REVIEW

**Comment by Effet** [comment]
please explain and give some data, that you tested it's compatibility.

**Comment by shuofan** [comment]
> please explain and give some data, that you tested it's compatibility.

When no string value is set for a cell, Mac OS Numbers copies the value from cell A1
https://erda.dev.terminus.io/terminus/dop/projects/9

**Review by sfwn — APPROVED** [review]

**Pull request merged**
