### PR TITLE
Fixed the problem of extension provider reading configuration failure and incorrect interface parameter parsing

### PR DESCRIPTION
**Pull request by ZLValien**
#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:

extension provider is in module dicehub

.yml cannot read env like map[string][]string.So read it as string and unmarshal  it when provider init.

Many interface parameters were originally processed by url.QueryUnescape(), but they were omitted during refac. Now add them

### CODE REVIEW

**Comment by sfwn** [comment]
Add labels.

**Comment by Effet** [comment]
add unit test for real menu data

**Comment by ZLValien** [comment]
> add unit test for real menu data

**Comment by ZLValien** [comment]
> add unit test for real menu data

done 。add unit test for real data

**Pull request closed without merging**
