### PR TITLE
fix: change flink fourth level domain to three

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of this PR
change flink fourth level domain to three

Add one of the following kinds:
/kind bug

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  change flink fourth level domain to three            |
| 🇨🇳 中文    | 将flink-ui的四级域名改为三级             |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sfwn — CHANGES_REQUESTED** [review]
what the domain actually looks like?
show me a example domain of before/after this pr pls.

**Comment by chengjoey** [comment]
image
image
set succeed and stopped flink status success

**Review by sfwn — APPROVED** [review]

**Pull request merged**
