### PR TITLE
fix: skip addon dice.yml validate

### PR DESCRIPTION
**Pull request by iutx**
#### What this PR does / why we need it:

skip addon dice.yml validate, some platform addon, such as registercenter don't need to validate. 

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn @sixther-dc 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  skip addon dice.yml validate            |
| 🇨🇳 中文    |    跳过 addon dice.yml 校验          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sfwn** [comment]
Can you give an example of an addon that does not require diceyml validating?

**Comment by iutx** [comment]
> Can you give an example of an addon that does not require diceyml validating?

```yaml
version: "2.0"
addons:
  nacos:
    plan: "nacos:basic"
    options:
      version: "1.1.0"
```

**Comment by iutx** [comment]
> Can you give an example of an addon that does not require diceyml validating?

For users, diceyml must containes `services` or `jobs`, means must can create runtime.

For Erda addons, may be created from pages, not pipeline.
image

**Review by sfwn — APPROVED** [review]

**Pull request merged**
