### PR TITLE
feat(cluster-manager): provider cluster dialer

### PR DESCRIPTION
**Pull request by iutx**
#### What this PR does / why we need it:
provider cluster dialer
image

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=317668&issueFilter__urlQuery=eyJzdGF0ZXMiOls0NDAyLDcxMDQsNzEwNSw0NDAzLDQ0MDQsNzEwNiw0NDA2LDQ0MDcsNDQxMiw0NTM4LDQ0MTMsNDQxNCw0NDE1LDQ0MTZdLCJhc3NpZ25lZUlEcyI6WyIxMDAxMDU1Il19&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&iterationID=1250&type=BUG)

#### Specified Reviewers:

/assign @sixther-dc 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |  provider cluster dialer            |
| 🇨🇳 中文    |    provider cluster dialer          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sfwn — CHANGES_REQUESTED** [review]
link to related erda issue please.

**Comment by iutx** [comment]
> link to related erda issue please.

**Review by sixther-dc — APPROVED** [review]
/approve

**Review by sixther-dc — APPROVED** [review]
/approve

**Review by sfwn — APPROVED** [review]

**Pull request merged**
