### PR TITLE
feat: remove manifest of quick-start

### PR DESCRIPTION
**Pull request by iutx**
#### What this PR does / why we need it:
remove manifest of quick-start
- install from static.erda.cloud (oss) with curl
- build source with [erda-release/quick-start](https://github.com/erda-project/erda-release/tree/master/quick-start)

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @sfwn @sixther-dc 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | remove manifest of quick-start             |
| 🇨🇳 中文    |   移除 quick-start            |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by sfwn — CHANGES_REQUESTED** [review]
OK, so we should add a link to erda-release's quick-start?

**Comment by sfwn** [comment]
> OK, so we should add a link to erda-release's quick-start?

@iutx I see it already links to `docs.erda.cloud`.

You should specify `build source with [erda-release/quick-start](https://github.com/erda-project/erda-release/tree/master/quick-start)` in the doc there, for reference.

**Comment by iutx** [comment]
> OK, so we should add a link to erda-release's quick-start?

I don‘t think we need to add links redirect to [erda-release](https://github.com/erda-project/erda-release).

User only needs to care about the installation docs (https://docs.erda.cloud/latest/manual/install/docker-install.html), perhaps it would be more appropriate to added at `CONTRIBUTING.md` in the future.

**Comment by iutx** [comment]
> > OK, so we should add a link to erda-release's quick-start?
> 
> @iutx I see it already links to `docs.erda.cloud`.
> 
> You should specify `build source with [erda-release/quick-start](https://github.com/erda-project/erda-release/tree/master/quick-start)` in the doc there, for reference.

good idea!

**Review by sfwn — APPROVED** [review]

**Pull request merged**
