### PR TITLE
feat: Add the scheme to the header when the automation test agent requests

### PR DESCRIPTION
**Pull request by kakj-go**
#### What this PR does / why we need it:
Add the scheme to the header when the automation test agent requests

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |    Add the scheme to the header when the automation test agent requests       |
| 🇨🇳 中文    |       自动化测试代理请求的时候将 scheme 加入到 header 中      |

### CODE REVIEW

**Comment by kakj-go** [comment]
test image: 
image

**Comment by kakj-go** [comment]
image

**Comment by sfwn** [comment]
why 'failed to find session'?

**Comment by kakj-go** [comment]
Environmental problems can now be solved

image

**Review by sfwn — APPROVED** [review]

**Pull request merged**
