### PR TITLE
fix typo existant->existent

### PR DESCRIPTION
**Pull request by mamil**
#### What type of this PR
/kind document

Add one of the following kinds:
/kind feature
/kind bug
/kind polish
/kind document

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |              |
| 🇨🇳 中文    |              |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by hoozecn — APPROVED** [review]
LGTM
/approve

**Comment by hoozecn** [comment]
@mamil Thanks for your contribute

**Comment by sfwn** [comment]
good first pr :)

**Pull request merged**
