### PR TITLE
Fix/pipeline events errors optimization

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of this PR

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:
optimization of pipeline task errors and events

#### Specified Reviewers:

/assign @your-reviewer
@sfwn 

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | optimization of pipeline task errors and events             |
| 🇨🇳 中文    | 优化流水线任务错误的展示和events的展示             |

### CODE REVIEW

**Comment by chengjoey** [comment]
image
image

**Comment by sfwn** [comment]
Do not display startTime,endTime,count if count = 1.

**Review by sfwn — APPROVED** [review]

**Pull request merged**
