### PR TITLE
fix(pipeline): loop tasks created many times due to network-error

### PR DESCRIPTION
**Pull request by chengjoey**
#### What this PR does / why we need it:
fix loop tasks created many times due to network-error

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJhc3NpZ25lZSI6WyIxMDAxMjA1Il19&id=308870&iterationID=1178&pId=0&type=BUG)

#### Specified Reviewers:

/assign @sfwn 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | fix loop tasks created many times due to network-error             |
| 🇨🇳 中文    |    修复了由于网络错误导致的循环任务重复创建          |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sfwn** [comment]
Please add a well-designed unit-test to cover this situation.

**Comment by chengjoey** [comment]
> Please add a well-designed unit-test to cover this situation.

added unit-test

**Review by sfwn — APPROVED** [review]

**Pull request merged**
