### PR TITLE
Readme modifications

### PR DESCRIPTION
**Pull request by hoozecn**
1. add navigations
2. change description of erda repositories
3. re-order some section

#### What type of this PR

Add one of the following kinds:
/kind document

#### Specified Reviewers:

/assign @skoo87

### CODE REVIEW

**Review by liuhaoyang — DISMISSED** [review]

**Comment by hoozecn** [comment]
@liuhaoyang Accepted by Mengjia

**Review by liuhaoyang — APPROVED** [review]

**Comment by hoozecn** [comment]
@liuhaoyang Fix: commit is not signed

**Review by Effet — APPROVED** [review]

**Pull request merged**
