### PR TITLE
fix: remove http-client.env.json

### PR DESCRIPTION
**Pull request by innerpeacez**
#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      remove http-client.env.json        |
| 🇨🇳 中文    |       删除 http-client.env.json       |

### CODE REVIEW

**Review by sfwn — CHANGES_REQUESTED** [review]
why remove this file?
if this file should not be submitted, you should add into .gitignore also.

**Comment by Effet** [comment]
what is the purpose of deleting this file?

**Comment by innerpeacez** [comment]
> why remove this file? if this file should not be submitted, you should add into .gitignore also.

useless. wrong commit. @dspo

**Comment by innerpeacez** [comment]
This file is not a commonly used file and does not need to be added .gitignore. So, should not be merged, so we should pay more attention to the review of the code.

**Comment by sfwn** [comment]
please ref to the wrong commit.

**Comment by innerpeacez** [comment]
> please ref to the wrong pr.

https://github.com/erda-project/erda/pull/2821

**Review by sfwn — APPROVED** [review]

**Pull request merged**
