### PR TITLE
Fixed the issue when two different applications with the same branch at the same time

### PR DESCRIPTION
**Pull request by QvodSoldier**
Fixed the issue when two different applications with the same branch …

#### What type of this PR
/kind bug

#### What this PR does / why we need it:
Fixed the issue when two different applications with the same branch at the same time

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=71418&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDQzNiJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

#### Specified Reviewers:

/assign @Effet @sfwn

### CODE REVIEW

**Review by Effet — APPROVED** [review]

**Comment by Effet** [comment]
@QvodSoldier is this pr need cherry pick to 1.2 or 1.1 ?

**Comment by QvodSoldier** [comment]
> @QvodSoldier is this pr need cherry pick to 1.2 or 1.1 ?

**Comment by QvodSoldier** [comment]
> @QvodSoldier is this pr need cherry pick to 1.2 or 1.1 ?

I think it is enough to merge to 1.2, although 1.1 also has this defect

**Pull request merged**
