### PR TITLE
doc: add v1.1 changeLog

### PR DESCRIPTION
**Pull request by daskyrk**
#### What type of this PR
/kind document

#### What this PR does / why we need it:
* Add v1.1 changeLog
* Update changeLog files directory

### CODE REVIEW

**Comment by sfwn** [comment]
lgtm.

Imagine a question:
- we need a fix for v1.1.3, so the version is v1.1.4
- And latest v1.2.1 is already released. 

Where should we put the v1.1.4 into? Upper to latest v1.2.1 or between v1.2.0 and v1.1.3.

**Comment by daskyrk** [comment]
> lgtm.
> 
> Imagine a question:
> 
> * we need a fix for v1.1.3, so the version is v1.1.4
> * And latest v1.2.1 is already released.
> 
> Where should we put the v1.1.4 into? Upper to latest v1.2.1 or between v1.2.0 and v1.1.3.

Good question, i think we should insert patch version into the ordered list. For better view the patch version, i add a table.

**Pull request merged**
