### PR TITLE
fix: dicehub extension internationalization

### PR DESCRIPTION
**Pull request by kakj-go**
#### What this PR does / why we need it:
The action and addon lists support internationalization

#### Which issue(s) this PR fixes:
- [Erda Cloud Issue Link](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/gantt?filter__urlQuery=eyJpdGVyYXRpb24iOls3NzJdLCJtZW1iZXIiOlsiMTAwMDU2MCJdfQ%3D%3D&id=206505&iterationID=772&pId=0&type=BUG)

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      The action and addon lists support internationalization        |
| 🇨🇳 中文    |        action 和 addon 列表支持国际化      |

### CODE REVIEW

**Comment by kakj-go** [comment]
test images:
config data:

image

image

CICD:

image

image

image

image

addon:

image

image

**Review by sfwn — APPROVED** [review]

**Pull request merged**
