### PR TITLE
when creating a pipeline to cache action information, add a lock to read the map

### PR DESCRIPTION
**Pull request by kakj-go**
#### What type of this PR

/kind bug

#### What this PR does / why we need it:
The passedDataWhenCreate method will read the map concurrently, which will cause the pipeline to restart

#### Which issue(s) this PR fixes:
erda-issue: [erda-issue](https://terminus-org.app.terminus.io/erda/dop/projects/387/issues/all?id=206764&issueFilter__urlQuery=eyJzdGF0ZUJlbG9uZ3MiOlsiT1BFTiIsIldPUktJTkciLCJXT05URklYIiwiUkVPUEVOIiwiUkVTT0xWRUQiXSwiYXNzaWduZWVJRHMiOlsiMTAwMDU2MCJdfQ%3D%3D&issueTable__urlQuery=eyJwYWdlTm8iOjEsICJwYWdlU2l6ZSI6MTB9&issueViewGroup__urlQuery=eyJ2YWx1ZSI6ImthbmJhbiIsImNoaWxkcmVuVmFsdWUiOnsia2FuYmFuIjoiZGVhZGxpbmUifX0%3D&iterationID=431&type=BUG)

### CODE REVIEW

**Comment by sfwn** [comment]
Test if have dead lock.

**Comment by kakj-go** [comment]
These methods are locked, but these methods do not call each other, they will be unlocked after the method ends, which does not meet the 4 elements of deadlock

**Review by sfwn — CHANGES_REQUESTED** [review]
If no environment can be used to test, you should test it locally at least.

**Review by sfwn — APPROVED** [review]

**Pull request merged**
