### PR TITLE
fix: fix slice init length

### PR DESCRIPTION
**Pull request by cuishuang**
#### What this PR does / why we need it:

The intention here should be to initialize a slice with a capacity of 8 rather than initializing the length of this slice. 

The only demo: https://go.dev/play/p/q1BcVCmvidW

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      fix slice init length        |
| 🇨🇳 中文    |         修复切片初始化的长度     |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chengjoey** [comment]
hi @cuishuang , thanks for you contribution, please fulfil changelog in pr description

/assign @sfwn

**Comment by cuishuang** [comment]
> hi @cuishuang , thanks for you contribution, please fulfil changelog in pr description
> 
> /assign @sfwn

Thanks. fulfiled

**Comment by cuishuang** [comment]
friendly ping~

**Comment by sfwn** [comment]
Yes, you're right!
Currently, this function works because the result of `strings.Join(rs, "")` happens to ignore empty strings.

**Review by sfwn — DISMISSED** [review]

**Comment by sfwn** [comment]
Hi @cuishuang , can you amend your commit and repush it to trigger GitHub CI ? Thank you!

**Comment by cuishuang** [comment]
> Hi @cuishuang , can you amend your commit and repush it to trigger GitHub CI ? Thank you!

Thanks. I rebase the new master branch.

**Review by sfwn — APPROVED** [review]

**Pull request merged**
