### PR TITLE
feature:set the state of envData in autotest-plan components to global state

### PR DESCRIPTION
**Pull request by ZLValien**
#### What type of this PR

/kind feature

#### What this PR does / why we need it:

feature:set the state of envData in autotest-plan components to global state

delete useless render

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |      set envData to global  state      |
| 🇨🇳 中文    |     将配置数据添加到全局状态里         |

### CODE REVIEW

**Comment by Effet** [comment]
proven it has been tested in dev.

**Comment by ZLValien** [comment]
> proven it has been tested in dev.

have been tested it in dev

**Review by Effet — APPROVED** [review]

**Pull request merged**
