### PR TITLE
fix: convert `project_id` to string

### PR DESCRIPTION
**Pull request by dspo**
#### What this PR does / why we need it:
feat: convert `project_id` to string in query condition for using index.

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | convert `project_id` to string in query condition for using index. |
| 🇨🇳 中文    | 查询 `s_pod_info` 时 `project_id` 转换成 string, 以修复用不上索引的问题 |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by jferic — COMMENTED** [review]
LGTM

**Review by sixther-dc — APPROVED** [review]
/approve

**Pull request merged**
