### PR TITLE
fix: remove steve cache ttl

### PR DESCRIPTION
**Pull request by CeerDecy**
#### What this PR does / why we need it:
remove steve cache ttl

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](https://erda.cloud/erda/dop/projects/387/issues/all?id=619173&iterationID=-1&type=TASK)

#### Specified Reviewers:

/assign @iutx 

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English |       remove steve cache ttl       |
| 🇨🇳 中文    |      取消Steve cache的过期时间        |

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by iutx — APPROVED** [review]
LGTM @sfwn

**Comment by sfwn** [comment]
Maybe you can simply accomplish this by set TTL to -1, or sth like this. @CeerDecy

**Comment by CeerDecy** [comment]
> Maybe you can simply accomplish this by set TTL to -1, or sth like this. @CeerDecy

can't set to never expire by setting `Expiration=-1`, and the cache code doesn't do anything special with `-1`. @sfwn 
image
image

**Review by sfwn — APPROVED** [review]

**Pull request merged**
