### PR TITLE
feat(scale): support scale the resource not restart pod

### PR DESCRIPTION
**Pull request by Muzry**
#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
- feat(scale): support scale the resource not restart pod

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)

#### Specified Reviewers:

/assign @luobily @sixther-dc 

#### Need cherry-pick to release versions?

Add comment like `/cherry-pick release/1.0` when this PR is merged.

> For details on the cherry pick process, see the [cherry pick requests](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md#how-to-cherry-pick-a-merged-pr) section under [CONTRIBUTING.md](https://github.com/erda-project/erda/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Review by luobily — APPROVED** [review]
/approve

**Comment by liuhaoyang** [comment]
Please add labels to let us know its status and scope of influence.

**Comment by Muzry** [comment]
> Please add labels to let us know its status and scope of influence.

I don't have the permission and how to label this pr？

**Pull request merged**
