### PR TITLE
Hotfix/pipeline support multi containers monitor

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of this PR

Add one of the following kinds:
/kind feature

#### What this PR does / why we need it:
support multi containers monitor

#### Which issue(s) this PR fixes:

- Fixes #your-issue_number
- [Erda Cloud Issue Link](paste your link here)
-  [master pr](https://github.com/erda-project/erda/pull/1585)

#### Specified Reviewers:

/assign @your-reviewer

#### ChangeLog

| Language | Changelog |
| --------- | ------------ |
| 🇺🇸 English | support multi containers monitor             |
| 🇨🇳 中文    |  支持任务多容器监控            |

### CODE REVIEW

**Comment by sfwn** [comment]
link master pr.

**Comment by sfwn** [comment]
Test in erda 1.2.

**Comment by chengjoey** [comment]
image
image
tested in erda test 1.2 env

**Review by sfwn — APPROVED** [review]

**Pull request merged**
